name: CI/CD Frontend

run-name: ${{ github.actor }} is working on the frontend

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['21.6.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Fix Prettier
        run: npm run format:fix

      - name: Run Prettier
        run: npm run format

      - name: Build project
        run: npm run build --if-present

      # Step 8: Run tests
      # - name: Run tests
      #   run: npm test

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t gamebotsfrontimage:0.0.1 .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CD_DOCKER_USERNAME }}
          password: ${{ secrets.CD_DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag gamebotsfrontimage:0.0.1 ${{ secrets.CD_DOCKER_USERNAME }}/gamebotsfrontimage:0.0.1

      - name: Push Docker image
        run: docker push ${{ secrets.CD_DOCKER_USERNAME }}/gamebotsfrontimage:0.0.1
